[package]
name = "rlox"
version = "0.0.1"
edition = "2021"

[features]
debug-trace = []

[dependencies]
dashmap = "=5.4"
drop_bomb = "=0.1"
either = "=1.8"
eyre = "=0.6"
fnv = "=1.0"
hashbrown = "=0.13"
lazy_static = "=1.4"
paste = "=1.0"
scoped-tls = "=1.0"
thiserror = "=1.0"
